name: build normal nodejs
on: ["workflow_dispatch"]

jobs:
  push:
    name: "yolks:nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 12-normal
          - 14-normal
          - 16-normal
          - 17-normal
          - 18-normal
          - 19-normal
          - 20-normal
          - 21-normal
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./nodejs
          file: ./nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/myzumi/yolks:nodejs_${{ matrix.tag }}
