name: build steamcmd
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - steamcmd/**
jobs:
  push:
    name: "steamcmd:${{ matrix.distro }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian
          - ubuntu
<<<<<<<< HEAD:.github/workflows/steamcmd.yml
          - dotnet
          - proton
          - proton_8   
          - sniper
    steps:
      - uses: actions/checkout@v4
========
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
>>>>>>>> 3798abab4ef49b5d1d9725f581a1eba7acccff8b:.github/workflows/installers.yml
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
<<<<<<<< HEAD:.github/workflows/steamcmd.yml
          context: ./steamcmd
          file: ./steamcmd/${{ matrix.distro }}/Dockerfile
          platforms: linux/amd64
========
          context: ./installers
          file: ./installers/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
>>>>>>>> 3798abab4ef49b5d1d9725f581a1eba7acccff8b:.github/workflows/installers.yml
          push: true
          tags: |
            ghcr.io/parkervcp/steamcmd:${{ matrix.distro }}
